// Code generated by "stringer -type=UserPriviledge"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[User-0]
	_ = x[Mod-1]
	_ = x[Admin-2]
}

const _UserPriviledge_name = "UserModAdmin"

var _UserPriviledge_index = [...]uint8{0, 4, 7, 12}

func (i UserPriviledge) String() string {
	if i >= UserPriviledge(len(_UserPriviledge_index)-1) {
		return "UserPriviledge(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UserPriviledge_name[_UserPriviledge_index[i]:_UserPriviledge_index[i+1]]
}
